#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NavigationDrawer.Resource", IsApplication=true)]

namespace NavigationDrawer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int planets_array = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int fastScrollEnabled = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int fastScrollHorizontalThumbDrawable = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fastScrollHorizontalTrackDrawable = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int fastScrollVerticalThumbDrawable = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int fastScrollVerticalTrackDrawable = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int font = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int fontProviderAuthority = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int fontProviderCerts = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int fontProviderFetchStrategy = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int fontProviderFetchTimeout = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int fontProviderPackage = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int fontProviderQuery = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int fontStyle = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int fontWeight = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int layoutManager = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int reverseLayout = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int spanCount = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int stackFromEnd = 2130837521;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F030000
			public const int abc_action_bar_embed_tabs = 2130903040;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F040000
			public const int notification_action_color_filter = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int notification_icon_bg_color = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int notification_material_background_media_default_color = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int primary_text_default_material_dark = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ripple_material_light = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int secondary_text_default_material_dark = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int secondary_text_default_material_light = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F050000
			public const int compat_button_inset_horizontal_material = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int compat_button_inset_vertical_material = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int compat_button_padding_horizontal_material = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int compat_button_padding_vertical_material = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int compat_control_corner_material = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int fastscroll_default_thickness = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int fastscroll_margin = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int fastscroll_minimum_range = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int horizontal_page_margin = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int item_touch_helper_swipe_escape_max_velocity = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int item_touch_helper_swipe_escape_velocity = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int margin_huge = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int margin_large = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int margin_medium = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int margin_small = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int margin_tiny = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int notification_action_icon_size = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int notification_action_text_size = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int notification_big_circle_margin = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int notification_content_margin_start = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int notification_large_icon_height = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int notification_large_icon_width = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int notification_main_column_padding_top = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int notification_media_narrow_margin = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int notification_right_icon_size = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int notification_right_side_padding_top = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int notification_small_icon_background_padding = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int notification_small_icon_size_as_large = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int notification_subtext_size = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int notification_top_pad = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int notification_top_pad_large_text = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int vertical_page_margin = 2131034144;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F060000
			public const int action_search = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int drawer_shadow = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int earth = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int ic_drawer = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int ic_launcher = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int jupiter = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int mars = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int mercury = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int neptune = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int notification_action_background = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int notification_bg = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int notification_bg_low = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int notification_bg_low_normal = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int notification_bg_low_pressed = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int notification_bg_normal = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int notification_bg_normal_pressed = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int notification_icon_background = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int notification_template_icon_bg = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int notification_template_icon_low_bg = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int notification_tile_bg = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int notify_panel_notification_icon_bg = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int sample_dashboard_item_background = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int saturn = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int tile = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int uranus = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int venus = 2131099673;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070000
			public const int action0 = 2131165184;
			
			// aapt resource value: 0x7F070006
			public const int actions = 2131165190;
			
			// aapt resource value: 0x7F070001
			public const int action_container = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int action_divider = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int action_image = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int action_text = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int action_websearch = 2131165189;
			
			// aapt resource value: 0x7F070007
			public const int async = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int blocking = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int button1 = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int cancel_action = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int chronometer = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int content_frame = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int drawer_layout = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int end_padder = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int forever = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int icon = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int icon_group = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int image = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int info = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int italic = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int item_touch_helper_previous_elevation = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int left_drawer = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int line1 = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int line3 = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int media_actions = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int normal = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int notification_background = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int notification_main_column = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int notification_main_column_container = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int right_icon = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int right_side = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int status_bar_latest_event_content = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int tag_transition_group = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int text = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int text2 = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int textView1 = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int time = 2131165221;
			
			// aapt resource value: 0x7F070026
			public const int title = 2131165222;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F080000
			public const int cancel_button_image_alpha = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int status_bar_notification_info_maxnum = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F090000
			public const int activity_main = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int activity_navigation_drawer = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int drawer_list_item = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int fragment_planet = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int notification_action = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int notification_action_tombstone = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int notification_media_action = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int notification_media_cancel_action = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int notification_template_big_media = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int notification_template_big_media_custom = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int notification_template_big_media_narrow = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int notification_template_big_media_narrow_custom = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int notification_template_custom_big = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int notification_template_icon_group = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int notification_template_lines_media = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public const int notification_template_media = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int notification_template_media_custom = 2131296272;
			
			// aapt resource value: 0x7F090011
			public const int notification_template_part_chronometer = 2131296273;
			
			// aapt resource value: 0x7F090012
			public const int notification_template_part_time = 2131296274;
			
			// aapt resource value: 0x7F090013
			public const int sample_dashboard_item = 2131296275;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F0A0000
			public const int navigation_drawer = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0B0000
			public const int action_websearch = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int app_name = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int app_not_available = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int drawer_close = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int drawer_open = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int intro_message = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int navigationdraweractivity_description = 2131427334;
			
			// aapt resource value: 0x7F0B0007
			public const int navigationdraweractivity_title = 2131427335;
			
			// aapt resource value: 0x7F0B0008
			public const int status_bar_notification_info_overflow = 2131427336;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0C0000
			public const int AppTheme = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int TextAppearance_Compat_Notification = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int TextAppearance_Compat_Notification_Info = 2131492866;
			
			// aapt resource value: 0x7F0C0003
			public const int TextAppearance_Compat_Notification_Info_Media = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public const int TextAppearance_Compat_Notification_Line2 = 2131492868;
			
			// aapt resource value: 0x7F0C0005
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131492869;
			
			// aapt resource value: 0x7F0C0006
			public const int TextAppearance_Compat_Notification_Media = 2131492870;
			
			// aapt resource value: 0x7F0C0007
			public const int TextAppearance_Compat_Notification_Time = 2131492871;
			
			// aapt resource value: 0x7F0C0008
			public const int TextAppearance_Compat_Notification_Time_Media = 2131492872;
			
			// aapt resource value: 0x7F0C0009
			public const int TextAppearance_Compat_Notification_Title = 2131492873;
			
			// aapt resource value: 0x7F0C000A
			public const int TextAppearance_Compat_Notification_Title_Media = 2131492874;
			
			// aapt resource value: 0x7F0C000B
			public const int Theme_Base = 2131492875;
			
			// aapt resource value: 0x7F0C000C
			public const int Theme_Sample = 2131492876;
			
			// aapt resource value: 0x7F0C000D
			public const int Widget = 2131492877;
			
			// aapt resource value: 0x7F0C000E
			public const int Widget_Compat_NotificationActionContainer = 2131492878;
			
			// aapt resource value: 0x7F0C000F
			public const int Widget_Compat_NotificationActionText = 2131492879;
			
			// aapt resource value: 0x7F0C0010
			public const int Widget_SampleContentContainer = 2131492880;
			
			// aapt resource value: 0x7F0C0011
			public const int Widget_SampleDashboard_Grid = 2131492881;
			
			// aapt resource value: 0x7F0C0012
			public const int Widget_SampleDashboard_Item = 2131492882;
			
			// aapt resource value: 0x7F0C0013
			public const int Widget_SampleDashboard_Item_Description = 2131492883;
			
			// aapt resource value: 0x7F0C0014
			public const int Widget_SampleDashboard_Item_Title = 2131492884;
			
			// aapt resource value: 0x7F0C0015
			public const int Widget_SampleMessage = 2131492885;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F020006,0x7F020007,0x7F020008,0x7F020009,0x7F02000A,0x7F02000B }
			public static int[] FontFamily = new int[] {
					2130837510,
					2130837511,
					2130837512,
					2130837513,
					2130837514,
					2130837515};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x7F020005,0x7F02000C,0x7F02000D }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130837509,
					2130837516,
					2130837517};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_font = 3;
			
			// aapt resource value: 4
			public const int FontFamilyFont_fontStyle = 4;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x10100C4,0x10100F1,0x7F020000,0x7F020001,0x7F020002,0x7F020003,0x7F020004,0x7F02000E,0x7F02000F,0x7F020010,0x7F020011 }
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130837504,
					2130837505,
					2130837506,
					2130837507,
					2130837508,
					2130837518,
					2130837519,
					2130837520,
					2130837521};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_fastScrollEnabled = 2;
			
			// aapt resource value: 3
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 3;
			
			// aapt resource value: 4
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 4;
			
			// aapt resource value: 5
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 5;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 6;
			
			// aapt resource value: 7
			public const int RecyclerView_layoutManager = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_reverseLayout = 8;
			
			// aapt resource value: 9
			public const int RecyclerView_spanCount = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_stackFromEnd = 10;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
